---
title: "Obesity Level Predictive Modeling"
author: "Kaylen Ton"
---

### Load packages

```{r - packages and data}

library(tidyverse)
library(tidymodels)
library(vip)

# For parallel processing when it comes to tuning multiple models (which can take longer)
library(parallelly)
library(future)
cores <- availableCores(logical = F)
plan(multisession, workers = cores)

```

### Load in and clean data

```{r}

mydata <- read_csv("ObesityData.csv")

cleaned_data <- mydata %>% 
  mutate(
    across(where(is.numeric), ~ round(.x, 2)),
    across(where(is.character), as.factor),
    Age = round(Age, 0)
  )

```

### EDA

```{r}

cleaned_data %>% 
  select_if(is.numeric) %>% 
  cor()

# The highest correlations between variables stays under |.50|
# Weight & Height -> 0.46226361 correlation

```

# **Modeling**

## Splitting Data

```{r}

# Set seed for reproducibility 
set.seed(73)

# Split data
split <- initial_split(cleaned_data, strata = NObeyesdad)

obesity_train <- training(split)
obesity_test <- testing(split)

# Preparing folds for cross validation and resampling
tree_folds <- vfold_cv(obesity_train, v = 10,
                       strata = NObeyesdad)
    
# Creating custom metrics
tree_metrics <- metric_set(accuracy, roc_auc, sens, spec)

```

# Model 1 - Base Decision Tree

```{r}

# Specify Model
base_tree_model <- decision_tree() %>% 
  set_engine('rpart') %>% 
  set_mode('classification')

# Create Recipe
tree_recipe <- recipe(NObeyesdad ~ ., data = obesity_train) %>%
  step_novel(all_nominal_predictors(), new_level = "other") %>% 
  step_dummy(all_nominal_predictors())

# Create Workflow
tree_workflow <- workflow() %>% 
  add_model(base_tree_model) %>% 
  add_recipe(tree_recipe)

# Fit resamples (CV)
tree_fit_resample <- tree_workflow %>%
  fit_resamples(resamples = tree_folds,
                metrics = tree_metrics)
    
tree_fit_rs_result <- tree_fit_resample %>% 
  collect_metrics(summarize = F)

tree_fit_rs_result %>%
  filter(.metric == 'roc_auc') %>% 
  group_by(id) %>%
  summarize(min_roc_auc = min(.estimate),
            median_roc_auc = median(.estimate),
            max_roc_auc = max(.estimate))

tree_fit_rs_result %>%
  group_by(.metric) %>%
  summarize(min = min(.estimate),
            median = median(.estimate),
            max = max(.estimate))

# 10 fold estimates (CV results)
#   .metric       min         median        max
# accuracy	  0.8490566	    0.8713926	    0.9032258
# roc_auc	    0.9629274	    0.9750240	    0.9852812	
# sens	      0.8455354	    0.8670822	    0.8976190	
# spec	      0.9748247	    0.9786377	    0.9840322	

# Fit & Test
base_tree_fit <- tree_workflow %>% 
  last_fit(split = split, metrics = tree_metrics)

# Collect Metrics    
base_tree_fit %>% 
  collect_metrics()

# Base decision tree model results
  # accuracy	    multiclass	  0.8433962	
  # sens	        macro	        0.8396276
  # spec	        macro	        0.9739000
  # roc_auc	      hand_till 	  0.9654471		

```

# Model 2 - Base Decision Tree Model w/ Tuned Hyper-Parameters

```{r}

# Specify Model
tune_tree_model <- decision_tree(
  cost_complexity = tune(),
  tree_depth = tune(),
  min_n = tune()
  ) %>% 
  set_engine('rpart') %>% 
  set_mode('classification')

# Create tuning grid for hyper-parameters
tree_grid <- grid_random(extract_parameter_set_dials(tune_tree_model), size = 20)

# Update workflow object with new model: tune_tree_model
tree_workflow <- tree_workflow %>%
  update_model(tune_tree_model)

# Tuning and resampling (cv)
tuning_tree_results <- tree_workflow %>% 
  tune_grid(resamples = tree_folds,
            grid = tree_grid,
            metrics = tree_metrics)

tuning_tree_results %>% 
  collect_metrics(summarize = FALSE) %>% 
  filter(.metric == "roc_auc") %>% 
  group_by(id) %>% 
  summarize(min_roc_auc = min(.estimate),
            median_roc_auc = median(.estimate),
            max_roc_auc = max(.estimate))

autoplot(tuning_tree_results)

tuning_tree_results %>% 
  show_best(metric = 'roc_auc', n = 5)

# Top 1 :
# cost_complexity     tree_depth  min_n   .metric   .estimator    mean          n    std_err
# 5.840945e-09        8           33      roc_auc   hand_till     0.9795647     10   0.001921038

best_tune_tree_model <- tuning_tree_results %>% 
  select_best(metric = 'roc_auc')

final_tune_tree_workflow <- tree_workflow %>% 
  finalize_workflow(best_tune_tree_model)

final_tune_tree_fit <- final_tune_tree_workflow %>% 
  last_fit(split = split, metrics = tree_metrics)

final_tune_tree_fit %>% 
  collect_metrics()

# Tuned Decision Tree Model Results
# accuracy multiclass     0.8962264 
# sens     macro          0.8940891 
# spec     macro          0.9826643 
# roc_auc  hand_till      0.9811199 

```

# Model 3.1 - Gradient Boosted Tree Model

```{r}

# Specify Model
gradient_boost_tree_model <- boost_tree() %>% 
  set_mode("classification") %>% 
  set_engine("xgboost")

# Last fit - train and test
boosted_fit <- gradient_boost_tree_model %>%
 last_fit(NObeyesdad ~ ., split = split, metrics = tree_metrics)

boosted_fit %>% 
  collect_metrics()

# Base gradient boosted tree model results
  # accuracy multiclass     0.9660377 
  # sens     macro          0.9656546 
  # spec     macro          0.9943455 
  # roc_auc  hand_till      0.9980934 

# Collect predictions
boosted_predictions <- boosted_fit %>% 
  collect_predictions()

boosted_predictions

# Visualize ROC curve
boosted_roc <- boosted_predictions %>% 
  roc_curve(truth = NObeyesdad, .pred_Insufficient_Weight:.pred_Overweight_Level_II,
        estimator = "macro")

ggplot(boosted_roc, aes(x = 1 - specificity, y = sensitivity, color = .level)) +
  geom_line(linewidth = .75, alpha = .75) +
  labs(color = "Obesity Level") +
  geom_abline(lty = 2, alpha = .5) +
  theme_light() +
  labs(title = "ROC Curve 3: Gradient Boosted Tree Model")

```

# Model 3.2 - Gradient Boosted Tree Model w/ Tuned Hyper-Parameters

```{r}

# Gradient Boosted Tree w/ Tuning
tune_gradient_boost_tree_model <- boost_tree(
    trees = tune(),
    learn_rate = tune(),
    tree_depth = tune(),
    sample_size = tune()
  ) %>% 
  set_mode("classification") %>% 
  set_engine("xgboost")

# Create tuning grid for hyper-parameters
gradient_tree_grid <- grid_random(extract_parameter_set_dials(tune_gradient_boost_tree_model), size = 30)

# Update workflow object with new model: tune_gradient_boost_tree_model
tree_workflow <- tree_workflow %>%
  update_model(tune_gradient_boost_tree_model)

# Tuning and resampling (cv)
tuning_gradient_tree_results <- tree_workflow %>% 
  tune_grid(resamples = tree_folds,
            grid = gradient_tree_grid,
            metrics = tree_metrics)

tuning_gradient_tree_results %>% 
  collect_metrics(summarize = FALSE) %>% 
  filter(.metric == "roc_auc") %>% 
  group_by(id) %>% 
  summarize(min_roc_auc = min(.estimate),
            median_roc_auc = median(.estimate),
            max_roc_auc = max(.estimate))

autoplot(tuning_gradient_tree_results)

tuning_gradient_tree_results %>% 
  show_best(metric = 'roc_auc', n = 5)

# Top 1 :
# trees   tree_depth  learn_rate  sample_size   .metric   .estimator    mean     n
# 1558            10      0.0175        0.835   roc_auc   hand_till     0.998    10

best_tune_tree_model <- tuning_gradient_tree_results %>% 
  select_best(metric = 'roc_auc')

final_tune_tree_workflow <- tree_workflow %>% 
  finalize_workflow(best_tune_tree_model)

final_tune_tree_fit <- final_tune_tree_workflow %>% 
  last_fit(split = split, metrics = tree_metrics)

final_tune_tree_fit %>% 
  collect_metrics()

# Tuned Gradient Boost Model Results
  # accuracy	    multiclass	  0.8962264
  # sens	        macro	        0.8940891
  # spec	        macro	        0.9826643
  # roc_auc	      hand_till	    0.9811199

```